############################################################################# 
#
# VFRAME
# MIT License
# Copyright (c) 2020 Adam Harvey and VFRAME
# https://vframe.io 
#
#############################################################################

# ---------------------------------------------------------------------------
# Logger
# ---------------------------------------------------------------------------

logger:
  verbosity: 4  # disable 0
  disable: False
  logfile: ''

# ---------------------------------------------------------------------------
# List all ModelZoo configuration files
# ---------------------------------------------------------------------------

modelzoo:
  # VFRAME models
  - filepath: 'models/detection/9n235.yaml'
  - filepath: 'models/detection/rbk250.yaml'
  - filepath: 'models/detection/face.yaml'
  # 3rd party models
  - filepath: 'models/detection/objects365.yaml'
  - filepath: 'models/detection/coco.yaml'

plugins:

  # ---------------------------------------------------------------------------
  # Core: Pipeline processor
  # ---------------------------------------------------------------------------
  
  - name: pipe
    description: Image processing pipeline
    pipe: True
    scripts:
      - filepath: commands/pipe  # core scripts


  # ---------------------------------------------------------------------------
  # Core: ModelZoo
  # ---------------------------------------------------------------------------

  - name: models
    description: Model scripts
    scripts:
      - filepath: commands/models


  # ---------------------------------------------------------------------------
  # Core: Utilities
  # ---------------------------------------------------------------------------

  - name: utils
    description: Utility scripts
    scripts:
      - filepath: commands/utils

  # ---------------------------------------------------------------------------
  # Core: Deduplication
  # ---------------------------------------------------------------------------

  - name: dedup
    description: Deduplication scripts
    scripts:
      - filepath: commands/dedup